CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_TRANSPORT_BLE=y
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y

# 增加蓝牙 L2CAP 发送最大传输单元 (MTU)
CONFIG_BT_L2CAP_TX_MTU=247
# 增加蓝牙 ACL 接收和发送缓冲区大小
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
# 增加系统工作队列的堆栈大小 (防止处理大型 Studio RPC 消息时内存溢出)
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
